# Generated by Django 3.0.7 on 2020-11-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_seller',
        ),
    ]
