# Generated by Django 3.0.7 on 2020-11-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sellerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
