# Generated by Django 3.0.7 on 2020-11-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201103_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='country',
            field=models.CharField(default='Zimbabwe', max_length=90),
            preserve_default=False,
        ),
    ]
