# Generated by Django 3.0.7 on 2020-11-23 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_requestreviewgroup_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
