# Generated by Django 3.0.7 on 2020-11-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_testmonial_your_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmonial',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
