# Generated by Django 3.0.7 on 2020-11-30 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_sellerprofile_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='brand_logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Photo'),
        ),
    ]
