# Generated by Django 3.0.7 on 2020-11-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_sellerprofile_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
