# Generated by Django 3.0.7 on 2020-11-30 20:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20201130_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
