# Generated by Django 3.0.7 on 2020-12-09 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20201130_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='bank_account',
        ),
    ]
