# Generated by Django 3.0.7 on 2020-11-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_revenue_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='sales',
            field=models.DecimalField(decimal_places=2, default=345.67, max_digits=10),
            preserve_default=False,
        ),
    ]
