# Generated by Django 3.0.7 on 2020-11-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_auto_20201107_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='recent',
            field=models.BooleanField(default=False),
        ),
    ]
