# Generated by Django 3.0.7 on 2020-11-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_auto_20201107_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='recent',
        ),
    ]
