# Generated by Django 3.0.7 on 2020-12-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_remove_revenue_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
