# Generated by Django 3.0.7 on 2020-12-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_revenue_claimed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=90)),
                ('bank_account', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='revenue',
            name='bank_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sell.BankDetails'),
        ),
    ]
