# Generated by Django 3.0.7 on 2020-12-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0008_auto_20201205_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_account',
            field=models.CharField(max_length=15),
        ),
    ]
