# Generated by Django 3.0.7 on 2020-11-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
