# Generated by Django 3.0.7 on 2020-11-13 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
