# Generated by Django 3.0.7 on 2020-11-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='your_message',
        ),
    ]
