# Generated by Django 3.0.7 on 2020-11-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_siteinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='email',
            field=models.CharField(max_length=90),
        ),
    ]
