# Generated by Django 3.0.7 on 2020-12-03 13:55

from django.db import migrations, models
import shop.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201202_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.ImageField(blank=True, upload_to=shop.helpers.RandomFileName('product-images')),
        ),
    ]
