# Generated by Django 3.0.7 on 2020-12-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20201203_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='whatsapp',
            field=models.CharField(default='263773841049', max_length=14),
            preserve_default=False,
        ),
    ]
