# Generated by Django 3.0.7 on 2021-01-19 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20201209_1703'),
        ('agent', '0002_agentprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent_earnings', to='order.Order'),
            preserve_default=False,
        ),
    ]
