# Generated by Django 3.0.7 on 2021-01-19 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_earning_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
