# Generated by Django 3.0.7 on 2020-10-31 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_seller'),
        ('order', '0002_order_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=90)),
                ('phone_number', models.CharField(max_length=14)),
                ('street_address', models.CharField(max_length=255)),
                ('apartment', models.CharField(max_length=90)),
                ('country', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_addresses', to='order.Order')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_shipments_addresses', to='users.Profile')),
            ],
        ),
    ]
