# Generated by Django 3.0.7 on 2020-10-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201031_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinginformation',
            old_name='street_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='email',
            field=models.EmailField(default='chaulapsx@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='postal_code',
            field=models.CharField(default='0000', max_length=20),
            preserve_default=False,
        ),
    ]
