# Generated by Django 3.0.7 on 2020-11-01 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20201031_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginformation',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='order.Order'),
        ),
    ]
