# Generated by Django 3.0.7 on 2020-11-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sellerprofile_user'),
        ('order', '0007_auto_20201101_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='users.SellerProfile'),
        ),
    ]
