# Generated by Django 3.0.7 on 2020-11-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20201109_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginformation',
            name='postal_code',
        ),
    ]
