# Generated by Django 3.0.7 on 2020-11-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_shippinginformation_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginformation',
            name='apartment',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
