# Generated by Django 3.0.7 on 2020-12-09 17:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_orderitem_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginformation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
